## Config file

# Log 
seed: 777
use_cuda: 1           # 1 for True, 0 for False

# dataset
speaker_no: 3
mix_lst_path: ./data/VoxCeleb2/mixture_data_list_3mix.csv
audio_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/VoxCeleb2/audio_clean/
reference_direc: /mnt/nas_sg/wulanchabu/zexu.pan/datasets/VoxCeleb2/orig/
audio_sr: 16000
ref_sr: 25

# dataloader
num_workers: 4
batch_size: 2         # 4-GPU training with a total effective batch size of 8
accu_grad: 0
effec_batch_size: 4   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 3         # truncate the utterances in dataloader, in seconds 

# network settings
init_from: None       # 'None' or a log name 'log_2024-07-22(18:12:13)'
causal: 0             # 1 for True, 0 for False
network_reference:
  cue: lip            # lip or speech or gesture or EEG
  backbone: resnet18  # resnet18 or shufflenetV2 or blazenet64
  emb_size: 256       # resnet18:256
network_audio:
  backbone: av_tfgridnet
  n_fft: 256
  stride: 128
  window: "hann"
  use_builtin_complex: False
  n_srcs:  1
  n_imics: 1
  n_layers: 6
  lstm_hidden_units: 192
  attn_n_head: 4
  attn_qk_output_channel: 4
  emb_dim: 48
  emb_ks: 4
  emb_hs: 1
  activation: "prelu"

# optimizer
loss_type: sisdr      # "snr", "sisdr", "hybrid"
init_learning_rate: 0.001
max_epoch: 150
clip_grad_norm: 5
