#!/bin/bash 
mode: 'inference'
use_cuda: 1 # 1 for True, 0 for False
num_gpu: 1
sampling_rate: 16000
network: "FRCRN_SE_16K"  ##network type
checkpoint_dir: "checkpoints/FRCRN_SE_16K"

input_path: "samples/scp/cv_demand_testset_16k.scp"  # an input dir or input scp file
output_dir: "outputs/FRCRN_SE_16K" ## output dir to store processed audio

# decode parameters
one_time_decode_length: 120 #maximum segment length for one-pass decoding (seconds), longer audio  will use segmented decoding
decode_window: 1 #one-pass decoding length
#
# FFT parameters
win_type: 'hanning'
win_len: 640
win_inc: 320
fft_len: 640
