#!/bin/bash 
mode: 'inference'
use_cuda: 1 # 1 for True, 0 for False
num_gpu: 1
sampling_rate: 16000
network: "MossFormerGAN_SE_16K"  ##network type
checkpoint_dir: "checkpoints/MossFormerGAN_SE_16K"

input_path: "samples/scp/cv_demand_testset_16k.scp"
output_dir: "outputs/MossFormerGAN_SE_16K" ## output dir to store processed audio

# decode parameters
one_time_decode_length: 10 #maximum segment length for one-pass decoding (seconds), longer audio  will use segmented decoding
decode_window: 10 #one-pass decoding length

# FFT parameters
win_type: 'hamming'
win_len: 400
win_inc: 100
fft_len: 400
